# we create a Docker image from source code
version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5436:5432 #{port in host(myPC)} : {port in Container}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456789
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
  #Create another container for "TEST"
#   test-database:
#     image: postgres:15.0
#     container_name: test-database
#     ports:
#       - 5435:5432 #{port in host(myPC)} : {port in Container}
#     #environment variables, like: db's username, password...
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: Abc123456789
#       POSTGRES_DB: testdb
#     networks:
#       - nestjs-network
networks:
  nestjs-network:
